### PR TITLE
Fix broken `serde::Deserialize` and `FromStr` impl of `keyPair`

### LINKED ISSUE #491: `KeyPair` `FromStr` and `Deserialize` impls crash
When trying to deserialize a `KeyPair` the thread crashes with

```
[libsecp256k1] illegal argument. rustsecp256k1_v0_6_1_ecmult_gen_context_is_built(&ctx->ecmult_gen_ctx)
```

this can be reproduced using the following test without special feature configurations by running `cargo test  test_broken_keypair_serde`. I originally tested using serde, but could simplify it to `FromStr`.

```rust
    #[test]
    fn test_broken_keypair_serde() {
        let ctx = crate::Secp256k1::new();
        let keypair = KeyPair::new(&ctx, &mut thread_rng());
        let msg = keypair.secret_key().secret_bytes().to_hex();
        dbg!(&msg);
        let parsed_key: KeyPair = msg.parse().unwrap();
        assert_eq!(parsed_key, keypair);
    }
```

I'm not familiar enough with the low-level C API of libsecp to propose a fix keeping the unsafe code but would propose to use the global context instead and feature gate these impls accordingly.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #491

### CODE REVIEW

**Comment by apoelstra** [comment]
When `global-context` is not enabled, can you switch to alternate code that creates a context inline?

Maybe we don't want to do that -- but disabling this at compile-time is a breaking change, so I'd rather merge the non-breaking version (and backport it to several other versions) first, so that we can do a minor release.

**Comment by elsirion** [comment]
I also just noticed that my PR #379 (adding a serde module for `KeyPair`) was completely redundant?! I must have depended on an old release of libsecp and just upstreamed the fix I applied in Fedimint without noticing @dr-orlovsky had implemented decoding directly in the meantime.

File: src/key.rs [hunk 1]
```diff
@@ -1057,9 +1057,13 @@ impl str::FromStr for KeyPair {
...
 
     fn from_str(s: &str) -> Result<Self, Self::Err> {
-        let ctx = unsafe {
-            Secp256k1::from_raw_all(ffi::secp256k1_context_no_precomp as *mut ffi::Context)
-        };
+        #[cfg(feature = "global-context")]
+        let ctx = SECP256K1;
+
+        #[cfg(not(feature = "global-context"))]
+        let ctx = Secp256k1::signing_only();
```
Comment (elsirion) [inline src/key.rs:1064]: I wish I could deduplicate that code, but the global context is of type `Secp256k1<All>` while we apparently only need a signing context, so I can't easily build a function returning `Cow<'static, Secp256k1<_>>` (it would change its signature depending on the feature flags which is bad imo).

How much slower is creating an `All` context?

Comment (apoelstra) [reply src/key.rs]: I don't understand the question. What code needs to be deduplicated?

**Comment by apoelstra** [comment]
Could you add a unit test for the serde impl as well?

File: src/key.rs [hunk 2]
```diff
@@ -1053,13 +1053,18 @@ impl<'a> From<&'a KeyPair> for PublicKey {
     }
 }
 
+#[cfg(feature = "alloc")]
```
Comment (elsirion) [inline src/key.rs:1056]: The `alloc` requirement due to calling `Secp256k1::signing_only()` is a bit annoying, but better than the `global-context` one

File: src/key.rs (hunk 1 above)
Comment (elsirion) [reply src/key.rs]: The code highlighted with the comment which initializes `cfg` depending on the feature set. At first I had a `get_context() -> Cow<'static, Secp256k1<Signing>>` function for that till I noticed the global context type is incompatible.

File: src/key.rs (hunk 2 above)
Comment (apoelstra) [reply src/key.rs:1056]: I wonder if we should have a non-`alloc` non-`global-context` version that just returns an error 100% of the time.

My goal here is really just that we don't break compilation for anybody, while replacing the current "always aborts the process" code with something else...I don't care too much **what** else since the current behavior is so bad :)

Comment (elsirion) [reply src/key.rs]: The code has gotten a bit hairy, but I think it should have the desired behavior now.

**Comment by apoelstra** [comment]
Lol! Ok, I'll accept this. I think we should return an actual error rather than panicking, but a panic is certainly better than an abort.

**Comment by apoelstra** [comment]
Actually, could you change the panic message to include "please enable the `global-context` feature of rust-secp256k1"?

**Review by apoelstra — DISMISSED** [review]
ACK 73990f2baf67e187fe5acab63d8f1909e4e9f401

**Comment by elsirion** [comment]
Added the hint to turn on `global-context`.

**Comment by elsirion** [comment]
> Lol! Ok, I'll accept this. I think we should return an actual error rather than panicking, but a panic is certainly better than an abort.

Panicking re-creates the existing behavior. If you actually want to have a proper error I think that should work too (with some more `cfg` attributes on the return values).

**Review by apoelstra — APPROVED** [review]
ACK 53c1354cc584cb897a2d94ea7dd4098af61c6deb

**Comment by apoelstra** [comment]
@elsirion sorry, one more ask -- can you add a commit which bumps the minor version number of this crate and adds a CHANGELOG entry for this?

**Review by apoelstra — APPROVED** [review]
ACK 1f327b478ae80e2f074c6a74da00c540f15c17a2
