### PR TITLE
Patch out any instances of printf in upstream

### LINKED ISSUE #660: Consistently getting compilation error when compiling to wasm32
Error log:

```
The following warnings were emitted during compilation:

warning: In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:
warning: In file included from depend/secp256k1/src/group.h:10:
warning: In file included from depend/secp256k1/src/field.h:10:
warning: depend/secp256k1/src/util.h:32:5: error: call to undeclared library function 'printf' with type 'int (const char *, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning:     printf("{");
warning:     ^
warning: depend/secp256k1/src/util.h:32:5: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
warning: depend/secp256k1/src/util.h:150:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning:     void *ret = malloc(size);
warning:                 ^
warning: depend/secp256k1/src/util.h:150:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
warning: 2 errors generated.
warning: In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:
warning: In file included from depend/secp256k1/src/group.h:10:
warning: In file included from depend/secp256k1/src/field.h:10:
warning: depend/secp256k1/src/util.h:32:5: error: call to undeclared library function 'printf' with type 'int (const char *, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning:     printf("{");
warning:     ^
warning: depend/secp256k1/src/util.h:32:5: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
warning: depend/secp256k1/src/util.h:150:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning:     void *ret = malloc(size);
warning:                 ^
warning: depend/secp256k1/src/util.h:150:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
warning: 2 errors generated.

error: failed to run custom build command for `secp256k1-sys v0.9.0`

Caused by:
  process didn't exit successfully: `/home/hunter/Projects/diba/bitmask-core/target/release/build/secp256k1-sys-0a4816c08568de6a/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("wasm32-unknown-unknown")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
  CC_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
  CC_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
  CFLAGS_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
  CFLAGS_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
  CC_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
  CC_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
  CFLAGS_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
  CFLAGS_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core/target/wasm32-unknown-unknown/release/build/secp256k1-sys-9b02d0dd0903a28a/out/wasm/wasm.o" "-c" "wasm/wasm.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core/target/wasm32-unknown-unknown/release/build/secp256k1-sys-9b02d0dd0903a28a/out/depend/secp256k1/contrib/lax_der_parsing.o" "-c" "depend/secp256k1/contrib/lax_der_parsing.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core/target/wasm32-unknown-unknown/release/build/secp256k1-sys-9b02d0dd0903a28a/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "-c" "depend/secp256k1/src/precomputed_ecmult_gen.c"
  cargo:warning=In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:

  cargo:warning=In file included from depend/secp256k1/src/group.h:10:

  cargo:warning=In file included from depend/secp256k1/src/field.h:10:

  cargo:warning=depend/secp256k1/src/util.h:32:5: error: call to undeclared library function 'printf' with type 'int (const char *, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  cargo:warning=    printf("{");

  cargo:warning=    ^

  cargo:warning=depend/secp256k1/src/util.h:32:5: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'

  cargo:warning=depend/secp256k1/src/util.h:150:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  cargo:warning=    void *ret = malloc(size);

  cargo:warning=                ^

  cargo:warning=depend/secp256k1/src/util.h:150:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'

  cargo:warning=2 errors generated.

  exit status: 1
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core/target/wasm32-unknown-unknown/release/build/secp256k1-sys-9b02d0dd0903a28a/out/wasm/wasm.o" "-c" "wasm/wasm.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core/target/wasm32-unknown-unknown/release/build/secp256k1-sys-9b02d0dd0903a28a/out/depend/secp256k1/contrib/lax_der_parsing.o" "-c" "depend/secp256k1/contrib/lax_der_parsing.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core/target/wasm32-unknown-unknown/release/build/secp256k1-sys-9b02d0dd0903a28a/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "-c" "depend/secp256k1/src/precomputed_ecmult_gen.c"
  cargo:warning=In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:

  cargo:warning=In file included from depend/secp256k1/src/group.h:10:

  cargo:warning=In file included from depend/secp256k1/src/field.h:10:

  cargo:warning=depend/secp256k1/src/util.h:32:5: error: call to undeclared library function 'printf' with type 'int (const char *, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  cargo:warning=    printf("{");

  cargo:warning=    ^

  cargo:warning=depend/secp256k1/src/util.h:32:5: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'

  cargo:warning=depend/secp256k1/src/util.h:150:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  cargo:warning=    void *ret = malloc(size);

  cargo:warning=                ^

  cargo:warning=depend/secp256k1/src/util.h:150:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'

  cargo:warning=2 errors generated.

  exit status: 1

  --- stderr


  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core/target/wasm32-unknown-unknown/release/build/secp256k1-sys-9b02d0dd0903a28a/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "-c" "depend/secp256k1/src/precomputed_ecmult_gen.c" with args "clang" did not execute successfully (status code exit status: 1).
```

### PR DESCRIPTION
**Pull request by apoelstra**
Rather than using a new patchfile, just `#define` it away. Also includes a commit which removes one of the existing patchfiles, which I discovered was out of date while auditing the others to see if they could be replaced by `#define`s. (No, they cannot.)

Fixes #660

### CODE REVIEW

File: secp256k1-sys/build.rs [hunk 1]
```diff
@@ -20,11 +20,16 @@ fn main() {
                .include("depend/secp256k1/include")
                .include("depend/secp256k1/src")
                .flag_if_supported("-Wno-unused-function") // some ecmult stuff is defined but not used upstream
+               .flag_if_supported("-Wno-unused-parameter") // patching out printf causes this warning
```
Comment (Kixunil) [inline secp256k1-sys/build.rs:23]: I think this can be solved more locally but I haven't used C for a while so I don't remember how.

**Review by Kixunil — APPROVED** [review]
ACK 942a0e5e2cf35e728dc75a7e20c68dd01c69308e

File: secp256k1-sys/build.rs (hunk 1 above)
Comment (apoelstra) [reply secp256k1-sys/build.rs:23]: There's no standard C way to do it. Any specific compiler would have annotations but they wouldn't work for others. (Of course, `flag_if_supported` also not universal. But `cc` makes an effort to translate it for the common compilers.)

And in any case, if I wanted a more local solution, I'd just patch out the offending methods entirely :).

**Comment by apoelstra** [comment]
@cryptoquick are you able to test this PR (or just its last commit) and see if it works for you?

**Comment by cryptoquick** [comment]
When I add these crates:

```toml
secp256k1 = { git = "https://github.com/apoelstra/rust-secp256k1", branch = "2023-11--define-not-patch" }
secp256k1-sys = { git = "https://github.com/apoelstra/rust-secp256k1", branch = "2023-11--define-not-patch" }
```

I get this error:

```
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling secp256k1-sys v0.9.0 (https://github.com/apoelstra/rust-secp256k1?branch=2023-11--define-not-patch#942a0e5e)
The following warnings were emitted during compilation:

warning: In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:
warning: In file included from depend/secp256k1/src/group.h:10:
warning: In file included from depend/secp256k1/src/field.h:10:
warning: depend/secp256k1/src/util.h:28:50: warning: unused parameter 'buf' [-Wunused-parameter]
warning: static void print_buf_plain(const unsigned char *buf, size_t len) {
warning:                                                  ^
warning: depend/secp256k1/src/util.h:148:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning:     void *ret = malloc(size);
warning:                 ^
warning: depend/secp256k1/src/util.h:148:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
warning: 1 warning and 1 error generated.
warning: In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:
warning: In file included from depend/secp256k1/src/group.h:10:
warning: In file included from depend/secp256k1/src/field.h:10:
warning: depend/secp256k1/src/util.h:28:50: warning: unused parameter 'buf' [-Wunused-parameter]
warning: static void print_buf_plain(const unsigned char *buf, size_t len) {
warning:                                                  ^
warning: depend/secp256k1/src/util.h:148:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning:     void *ret = malloc(size);
warning:                 ^
warning: depend/secp256k1/src/util.h:148:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
warning: 1 warning and 1 error generated.

error: failed to run custom build command for `secp256k1-sys v0.9.0 (https://github.com/apoelstra/rust-secp256k1?branch=2023-11--define-not-patch#942a0e5e)`

Caused by:
  process didn't exit successfully: `/home/hunter/Projects/diba/bitmask-core-5/target/release/build/secp256k1-sys-2782e3689c5032f0/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("wasm32-unknown-unknown")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
  CC_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
  CC_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
  CFLAGS_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
  CFLAGS_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
  CC_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
  CC_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
  CFLAGS_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
  CFLAGS_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
  CC_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
  CC_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
  CFLAGS_wasm32-unknown-unknown = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
  CFLAGS_wasm32_unknown_unknown = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core-5/target/wasm32-unknown-unknown/release/build/secp256k1-sys-750d394d56fd67d3/out/wasm/wasm.o" "-c" "wasm/wasm.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core-5/target/wasm32-unknown-unknown/release/build/secp256k1-sys-750d394d56fd67d3/out/depend/secp256k1/contrib/lax_der_parsing.o" "-c" "depend/secp256k1/contrib/lax_der_parsing.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core-5/target/wasm32-unknown-unknown/release/build/secp256k1-sys-750d394d56fd67d3/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "-c" "depend/secp256k1/src/precomputed_ecmult_gen.c"
  cargo:warning=In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:

  cargo:warning=In file included from depend/secp256k1/src/group.h:10:

  cargo:warning=In file included from depend/secp256k1/src/field.h:10:

  cargo:warning=depend/secp256k1/src/util.h:28:50: warning: unused parameter 'buf' [-Wunused-parameter]

  cargo:warning=static void print_buf_plain(const unsigned char *buf, size_t len) {

  cargo:warning=                                                 ^

  cargo:warning=depend/secp256k1/src/util.h:148:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  cargo:warning=    void *ret = malloc(size);

  cargo:warning=                ^

  cargo:warning=depend/secp256k1/src/util.h:148:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'

  cargo:warning=1 warning and 1 error generated.

  exit status: 1
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core-5/target/wasm32-unknown-unknown/release/build/secp256k1-sys-750d394d56fd67d3/out/wasm/wasm.o" "-c" "wasm/wasm.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core-5/target/wasm32-unknown-unknown/release/build/secp256k1-sys-750d394d56fd67d3/out/depend/secp256k1/contrib/lax_der_parsing.o" "-c" "depend/secp256k1/contrib/lax_der_parsing.c"
  exit status: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core-5/target/wasm32-unknown-unknown/release/build/secp256k1-sys-750d394d56fd67d3/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "-c" "depend/secp256k1/src/precomputed_ecmult_gen.c"
  cargo:warning=In file included from depend/secp256k1/src/precomputed_ecmult_gen.c:3:

  cargo:warning=In file included from depend/secp256k1/src/group.h:10:

  cargo:warning=In file included from depend/secp256k1/src/field.h:10:

  cargo:warning=depend/secp256k1/src/util.h:28:50: warning: unused parameter 'buf' [-Wunused-parameter]

  cargo:warning=static void print_buf_plain(const unsigned char *buf, size_t len) {

  cargo:warning=                                                 ^

  cargo:warning=depend/secp256k1/src/util.h:148:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  cargo:warning=    void *ret = malloc(size);

  cargo:warning=                ^

  cargo:warning=depend/secp256k1/src/util.h:148:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'

  cargo:warning=1 warning and 1 error generated.

  exit status: 1

  --- stderr


  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-I" "wasm/wasm-sysroot" "-I" "wasm/wasm-sysroot" "-Wall" "-Wextra" "-DSECP256K1_API=" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_SCHNORRSIG=1" "-DENABLE_MODULE_EXTRAKEYS=1" "-DENABLE_MODULE_ELLSWIFT=1" "-Dprintf(...)=" "-DECMULT_GEN_PREC_BITS=4" "-DECMULT_WINDOW_SIZE=15" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-o" "/home/hunter/Projects/diba/bitmask-core-5/target/wasm32-unknown-unknown/release/build/secp256k1-sys-750d394d56fd67d3/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "-c" "depend/secp256k1/src/precomputed_ecmult_gen.c" with args "clang" did not execute successfully (status code exit status: 1).
```

Is this the proper way to test this PR?

**Comment by apoelstra** [comment]
Thanks! Yes, it looks like you're testing it correctly.

Very strange that your compiler is getting upset at the use of `malloc` inside of `checked_malloc`, which isn't even called anywhere in the library. The strangeness is because this has been the case for years, but til now nobody has complained.

I will add to this PR to replace `checked_malloc` with a stub that unconditionally calls the error callback, which should address this issue. Though possibly there will be more errors to come.

**Comment by tcharding** [comment]
>   cargo:warning=depend/secp256k1/src/util.h:28:50: warning: unused parameter 'buf' [-Wunused-parameter]
>   cargo:warning=static void print_buf_plain(const unsigned char *buf, size_t len) {

I get these warnings as well, and it seems related to the `flag_if_supported` thing I tried to remove in #661, using plain `flag` removes the warning on my machine.

**Comment by tcharding** [comment]
Ok, I got rid of all warnings on my machine by using this branch as well as
```rust
    // WASM headers and size/align defines.
    if env::var("CARGO_CFG_TARGET_ARCH").unwrap() == "wasm32" {
        base_config.include("wasm/wasm-sysroot")
            // upstream sometimes introduces calls to printf, which we cannot compile
            // with WASM due to its lack of libc. printf is never necessary and we can
            // just #define it away.
            .define("printf(...)", Some(""))
            .flag("-Wno-unused-parameter") // patching out printf causes this warning
	    .flag("-Wno-unused-function") // some ecmult stuff is defined but not used upstream      
            .flag("-Wno-implicit-function-declaration")
            .file("wasm/wasm.c");
    }
```

I believe its ok to use `flag` instead of `flag_if_supported` because we know wasm32 targets use clang and clang supports these flags.

File: secp256k1-sys/build.rs [hunk 2]
```diff
@@ -20,11 +20,16 @@ fn main() {
...
                .define("SECP256K1_API", Some(""))
                .define("ENABLE_MODULE_ECDH", Some("1"))
                .define("ENABLE_MODULE_SCHNORRSIG", Some("1"))
                .define("ENABLE_MODULE_EXTRAKEYS", Some("1"))
-               .define("ENABLE_MODULE_ELLSWIFT", Some("1"));
+               .define("ENABLE_MODULE_ELLSWIFT", Some("1"))
+               // upstream sometimes introduces calls to printf, which we cannot compile
+               // with WASM due to its lack of libc. printf is never necessary and we can
+               // just #define it away.
+               .define("printf(...)", Some(""));
```
Comment (tcharding) [inline secp256k1-sys/build.rs:32]: I think we should only use this if the target is wasm ie., put it in the 
```rust
    // WASM headers and size/align defines.
    if env::var("CARGO_CFG_TARGET_ARCH").unwrap() == "wasm32" {
```

Comment (tcharding) [reply secp256k1-sys/build.rs:32]: Also the `-Wno-unused-paramater`

Comment (apoelstra) [reply secp256k1-sys/build.rs:32]: Why?

**Comment by apoelstra** [comment]
> I believe its ok to use `flag` instead of `flag_if_supported` because we know wasm32 targets use clang and clang supports these flags.

Ok, but what about every other target we support? Do we know that they will use gcc or clang?

**Comment by cryptoquick** [comment]
I'm not sure gcc figures into wasm compilation. I'm using clang. Here are the details on my system:
https://github.com/rust-bitcoin/rust-secp256k1/issues/660#issuecomment-1788040215

File: secp256k1-sys/build.rs (hunk 2 above)
Comment (tcharding) [reply secp256k1-sys/build.rs:32]: Because there is a bug in `cc::Build::flag_if_supported` so we are getting loads of warnings. Well on my machine anyways.

File: secp256k1-sys/build.rs (hunk 1 above)
Comment (Kixunil) [reply secp256k1-sys/build.rs:23]: I mean something like using `(void)x` works IIRC which can be used in the define. But I don't know how to apply it to multiple arguments.

**Comment by tcharding** [comment]
Here is the solution to the wasm/flag_if_supported thing: https://github.com/rust-lang/cc-rs/pull/839

**Comment by Kixunil** [comment]
@tcharding so looks like @cryptoquick just needs to run `cargo update -p cc`?

**Comment by cryptoquick** [comment]
@Kixunil Tried that, but I'm already running cc@1.0.83. I noticed there was an update to libc v0.2.150, from 149, but that did not help.

**Comment by Kixunil** [comment]
> the fix that was merged has not yet been released

Oh, didn't notice. Perhaps test with their master branch using `[patch]`?

File: secp256k1-sys/depend/secp256k1/src/util.h [hunk 3]
```diff
@@ -145,11 +145,9 @@ static const rustsecp256k1_v0_9_0_callback default_error_callback = {
 #endif
 
 static SECP256K1_INLINE void *checked_malloc(const rustsecp256k1_v0_9_0_callback* cb, size_t size) {
```
Comment (Kixunil) [inline secp256k1-sys/depend/secp256k1/src/util.h:147]: Maybe delete it completely to ensure it's not called by accident?

Comment (apoelstra) [reply secp256k1-sys/depend/secp256k1/src/util.h:147]: Then I would need to delete all the functions that call it, and so on, which is much more invasive.

Comment (Kixunil) [reply secp256k1-sys/depend/secp256k1/src/util.h:147]: Sucks. Also I wonder how does it interact with the system library. Will anything break if it has different code?

Comment (apoelstra) [reply secp256k1-sys/depend/secp256k1/src/util.h:147]: No. It's not an exposed function, it's only used internally.

File: secp256k1-sys/build.rs (hunk 2 above)
Comment (tcharding) [reply secp256k1-sys/build.rs:32]: > Why?

Did you  mean why do I think we should put the `.define` on the wasm-only `cc::Build` or why the "Also `the -Wno-unused-parameter`? Ignore the second one, and for the first, I thought this because the code comment specifically mentions that this is a wasm problem so it seems logical to put it in the wasm-only place.

Comment (apoelstra) [reply secp256k1-sys/build.rs:32]: I don't think it's wasm-only. It would be any linker that tries to resolve libc symbols before pruning unused code.

**Comment by tcharding** [comment]
AFAICT this is right to go, ACK 7a0c60edcd976bd55abf1490aa8454ef2d1a7caf

**Review by Kixunil — APPROVED** [review]
ACK 7a0c60edcd976bd55abf1490aa8454ef2d1a7caf

**Comment by apoelstra** [comment]
Heh, github warned me that I'm bypassing the "one ack from a maintainer" rule. But I think that something I authored, with 2 acks from rust-bitcoin maintainers, and the original bug reporter saying that it helped, is ok to merge.

**Comment by cryptoquick** [comment]
Just tried the master branch with wasm-pack, it works great, thanks!
